"""alert telegram gonderim bayragi

Revision ID: 1d1132452ebc
Revises: 34ee36d362bc
Create Date: 2026-08-15 10:01:04.565499

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1d1132452ebc'
down_revision: str | Sequence[str] | None = '34ee36d362bc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_gonderildi', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_alerts_telegram_gonderildi'), ['telegram_gonderildi'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_telegram_gonderildi'))
        batch_op.drop_column('telegram_gonderildi')

    # ### end Alembic commands ###
