"""ilk sema

Revision ID: 34ee36d362bc
Revises: 
Create Date: 2026-08-15 09:10:02.902194

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '34ee36d362bc'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_health',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('basarili', sa.Integer(), nullable=True),
    sa.Column('basarisiz', sa.Integer(), nullable=True),
    sa.Column('son_durum', sa.String(), nullable=True),
    sa.Column('son_kontrol', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('domain_health', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_domain_health_domain'), ['domain'], unique=True)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(), nullable=False),
    sa.Column('kategori', sa.String(), nullable=True),
    sa.Column('ad_gecici', sa.Boolean(), nullable=True),
    sa.Column('guncel_fiyat', sa.Float(), nullable=True),
    sa.Column('guncel_satici', sa.String(), nullable=True),
    sa.Column('guncel_kaynak_id', sa.Integer(), nullable=True),
    sa.Column('son_kontrol', sa.DateTime(), nullable=True),
    sa.Column('puan', sa.Float(), nullable=True),
    sa.Column('yorum_sayisi', sa.Integer(), nullable=True),
    sa.Column('kontrol_araligi_dk', sa.Integer(), nullable=True),
    sa.Column('izleyen_sayisi', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_kategori'), ['kategori'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('telegram_chat_id', sa.String(), nullable=True),
    sa.Column('telegram_token', sa.String(), nullable=True),
    sa.Column('telegram_token_biter', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_telegram_chat_id'), ['telegram_chat_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_telegram_token'), ['telegram_token'], unique=False)

    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('host', sa.String(), nullable=False),
    sa.Column('satici', sa.String(), nullable=True),
    sa.Column('toplayici', sa.Boolean(), nullable=True),
    sa.Column('son_fiyat', sa.Float(), nullable=True),
    sa.Column('son_guven', sa.String(), nullable=True),
    sa.Column('durum', sa.String(), nullable=True),
    sa.Column('son_kontrol', sa.DateTime(), nullable=True),
    sa.Column('hata_serisi', sa.Integer(), nullable=True),
    sa.Column('bekleyen_fiyat', sa.Float(), nullable=True),
    sa.Column('asiri_supheli_seri', sa.Integer(), nullable=True),
    sa.Column('bozuk_uyarildi', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_host'), ['host'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_url'), ['url'], unique=True)

    op.create_table('watch_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(), nullable=False),
    sa.Column('hedef_butce', sa.Float(), nullable=True),
    sa.Column('sablon', sa.String(), nullable=True),
    sa.Column('son_bildirim_ts', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('fiyat', sa.Float(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_readings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_readings_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_readings_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_readings_ts'), ['ts'], unique=False)

    op.create_table('watches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=True),
    sa.Column('hedef_fiyat', sa.Float(), nullable=True),
    sa.Column('acil_fiyat', sa.Float(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('kilitli', sa.Boolean(), nullable=True),
    sa.Column('kilitli_fiyat', sa.Float(), nullable=True),
    sa.Column('sustur_bitis', sa.DateTime(), nullable=True),
    sa.Column('son_bildirim_ts', sa.DateTime(), nullable=True),
    sa.Column('son_bildirim_fiyat', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['set_id'], ['watch_sets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id', name='uix_watch_user_product')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('watch_id', sa.Integer(), nullable=True),
    sa.Column('tur', sa.String(), nullable=False),
    sa.Column('baslik', sa.String(), nullable=False),
    sa.Column('mesaj', sa.String(), nullable=False),
    sa.Column('okundu', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['watch_id'], ['watches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_user_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_created_at'))

    op.drop_table('alerts')
    op.drop_table('watches')
    with op.batch_alter_table('price_readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_readings_ts'))
        batch_op.drop_index(batch_op.f('ix_price_readings_source_id'))
        batch_op.drop_index(batch_op.f('ix_price_readings_product_id'))

    op.drop_table('price_readings')
    op.drop_table('watch_sets')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_url'))
        batch_op.drop_index(batch_op.f('ix_sources_host'))

    op.drop_table('sources')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_telegram_token'))
        batch_op.drop_index(batch_op.f('ix_users_telegram_chat_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_kategori'))

    op.drop_table('products')
    with op.batch_alter_table('domain_health', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_domain_health_domain'))

    op.drop_table('domain_health')
    # ### end Alembic commands ###
